### PR TITLE
Fix validation of exclusiveMinimum and exclusiveMaximum

### PR DESCRIPTION
**Pull request by cheesinglee**
Signed-off-by: Chee Sing Lee <lee@bigml.com>

### CODE REVIEW

**Comment by jaor** [comment]
Looks good, but would you mind adding a little test or two? Thanks!

**Comment by cheesinglee** [comment]
Oops, sorry about that. I've modified the existing min/max tests.

**Comment by jaor** [comment]
merged!

**Comment by jaor** [comment]
i've pushed to clojars version 0.6

**Pull request merged**
